# Generated by Django 4.2.6 on 2023-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0003_alter_joblisting_jobimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='jobImage',
            field=models.ImageField(upload_to='job-images/'),
        ),
    ]
